name: RuboCop

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: rubocop

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby 3.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true

    - name: Run RuboCop
      run: bundle exec rubocop --parallel
